Update rpi4_reference_dunfell.json
rdkcentral/BundleGen pull request #108
Opened 2023-06-22 12:52 UTC by sravanthi298

updated rpi4_reference_dunfell.json for DAC-cobalt

2023-06-22 13:22 UTC, sverkoye requested changes

2023-06-22 13:22 UTC, sverkoye commented on templates/generic/rpi4_reference_dunfell.json
> +            },
This binds the whole /tmp from the host. That is too much. For the rialto socket add this:

            {
                "source": "/tmp/{id}",
                "destination": "/tmp/rialto-0",
                "type": "bind",
                "options": [
                    "rbind",
                    "rw",
                    "X-dobby.optional"
                ]
            }

Same as I do here: https://github.com/rdkcentral/BundleGen/blob/c6c2922d4889643ae69ada992c19126e310ecec7/templates/generic/rpi3_reference_dunfell.json#L89

2023-06-22 13:22 UTC, sverkoye commented on templates/generic/rpi4_reference_dunfell.json
> -            "RIALTO_SOCKET_PATH=/tmp/rialto-0"
This must stay /tmp/rialto-0 if you mount bind the rialto socket as I mentioned above.

2023-06-22 13:22 UTC, sverkoye commented on templates/generic/rpi4_reference_dunfell.json
> +            "LD_LIBRARY_PATH=/usr/lib:/usr/lib/wpeframework/plugins",
Are you mounting framework plugins under this container? If not, then adding that path is useless and only confusing.

2023-06-27 04:48 UTC, closed without merging

2023-06-27 04:49 UTC, sravanthi298 commented
With latest Rpi4 OCI bundle, DAC-cobalt is working fine.

 These changes are not required now. Hence closing this PR.