RDK-34519 [DAC] Update BundleGen to support latest Dobby functionality
rdkcentral/BundleGen pull request #81
Opened 2022-12-14 07:31 UTC by PriyaPesala

2022-12-15 12:11 UTC, TeknoVenus requested changes
Please also rebase your changes so git history only contains the relevant commits

2022-12-15 14:46 UTC, PriyaPesala commented on bundlegen/core/bundle_processor.py
> +                self._add_annotation('run.oci.hooks.stderr','/dev/stderr')
Added in latest patchset

2022-12-15 14:47 UTC, PriyaPesala commented on bundlegen/core/bundle_processor.py
> +                    "required": True,
Removed in latest patchset

2022-12-15 14:47 UTC, PriyaPesala commented on bundlegen/core/bundle_processor.py
> +                        "journaldOptions": {
Removed in latest patchset

2022-12-15 14:47 UTC, PriyaPesala commented on bundlegen/core/bundle_processor.py
> +        if self.app_metadata['ipc']['enable']:
Updated in latest patchset

2022-12-15 14:47 UTC, PriyaPesala commented on bundlegen/core/bundle_processor.py
> +        if self.app_metadata['minidump']['enable']:
Updated in latest patchset

2022-12-15 14:47 UTC, PriyaPesala commented on bundlegen/core/bundle_processor.py
> +        if self.app_metadata['oomcrash']['enable']:
Updated in latest patchset

2022-12-15 14:47 UTC, PriyaPesala commented on bundlegen/core/bundle_processor.py
> +            plugin = app_gpu_bytes
Removed this variable and updated latest patchset

2022-12-15 14:47 UTC, PriyaPesala commented on bundlegen/schema/appMetadataSchema.json
> +        "oomcrush": {
Modified in latest patchset

2023-01-03 07:12 UTC, PriyaPesala commented
> Please also rebase your changes so git history only contains the relevant commits

In latest patchset changes are rebased

2023-01-03 14:21 UTC, TeknoVenus approved these changes

2023-01-03 14:21 UTC, merged